### ISSUE TITLE
BrokenPipeError when trying to run the demo 

### ISSUE THREAD

**Issue by mylad13** [Haiyang-W/MAVN#1]
Hi. I made tried running the demo following the instructions in the package's readme file, but I am faced with the following error:

(MAVN36) farjadnm@PC-SIROUSPOUR14:~/MAVN$ python demo.py -n1 --auto_gpu_config 1 --total_num_scenes 1 --task_config ./config/CommonGoal_two_locobot.yaml
INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /home/farjadnm/MAVN/gibson2/./data/assets
INFO:root:Dataset path: /home/farjadnm/MAVN/gibson2/./data/g_dataset
pybullet build time: May 20 2022 19:41:54
/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/site-packages/gym/core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
/home/farjadnm/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Auto GPU config:
Number of processes: 1
Number of processes on GPU 0: 1
Number of processes per GPU: 1
INFO:root:Importing iGibson (gibson2 module)
INFO:root:Assets path: /home/farjadnm/MAVN/gibson2/./data/assets
INFO:root:Dataset path: /home/farjadnm/MAVN/gibson2/./data/g_dataset
pybullet build time: May 20 2022 19:41:54
/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/site-packages/gym/core.py:27: UserWarning: WARN: Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+
  "Gym minimally supports python 3.6 as the python foundation not longer supports the version, please update your version to 3.7+"
/home/farjadnm/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Auto GPU config:
Number of processes: 1
Number of processes on GPU 0: 1
Number of processes per GPU: 1
INFO:root:Using device 0 for rendering
INFO:root:Using cuda device 0 for pytorch
******************PyBullet Logging Information:
PyBullet Logging Information******************
INFO:root:Building scene: Wainscott
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 168, in _worker_env
    env = env_fn(*env_fn_args)  # single environment
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 57, in init_env
    physics_timestep=1 / 40.0, render_to_tensor=render_to_tensor, device_idx=devices, rank=rank, seed=seed_num)
  File "/home/farjadnm/MAVN/env/make_collavn_env.py", line 55, in __init__
    rank=rank)
  File "/home/farjadnm/MAVN/env/mabase_env.py", line 56, in __init__
    render_to_tensor=render_to_tensor)
  File "/home/farjadnm/MAVN/env/base_env.py", line 47, in __init__
    self.load()
  File "/home/farjadnm/MAVN/env/mabase_env.py", line 227, in load
    super(MaBase_ImgGoal_NavigateEnv, self).load()
  File "/home/farjadnm/MAVN/env/base_env.py", line 87, in load
    self.simulator.import_scene(scene, load_texture=self.config.get('load_texture', True))
  File "/home/farjadnm/MAVN/gibson2/core/simulator.py", line 135, in wrapped_load_func
    res = load_func(*args, **kwargs)
  File "/home/farjadnm/MAVN/gibson2/core/simulator.py", line 155, in import_scene
    new_objects = scene.load()
  File "/home/farjadnm/MAVN/gibson2/core/physics/scene.py", line 292, in load
    self.load_floor_metadata()
  File "/home/farjadnm/MAVN/gibson2/core/physics/scene.py", line 125, in load_floor_metadata
    floor_height_path = os.path.join(get_model_path(self.model_id), 'floors.txt')
  File "/home/farjadnm/MAVN/gibson2/utils/assets_utils.py", line 7, in get_model_path
    assert model_id in os.listdir(data_path) or model_id == 'stadium', "Model {} does not exist".format(model_id)
FileNotFoundError: [Errno 2] No such file or directory: '/home/farjadnm/MAVN/gibson2/./data/g_dataset'
Traceback (most recent call last):
  File "demo.py", line 78, in <module>
    main()
  File "demo.py", line 57, in main
    envs = make_parallel_env(args.task_config, args, data_split, render_to_tensor=render_to_tensor, mode='headless', gpu_id_list=gpu_id_list)
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 604, in make_parallel_env
    envs = construct_envs(config_filename, args, scenes_split, mode, render_to_tensor, gpu_id_list)
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 595, in construct_envs
    env_fn_args=args_list,
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 130, in __init__
    read_fn() for read_fn in self._connection_read_fns
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 130, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method ProcessPyEnvironment.__del__ of <env.paralle_env.ProcessPyEnvironment object at 0x7f527c04ed30>>
Traceback (most recent call last):
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 479, in __del__
    self.close()
  File "/home/farjadnm/MAVN/env/paralle_env.py", line 369, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/farjadnm/anaconda3/envs/MAVN36/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

I get the same error running this in an environment with python 3.7 as well. 
Can you please help me fix this issue?
Thanks!

**Comment by TakieddineSOUALHI** [comment]
You need to download the gibson data set in : /home/farjadnm/MAVN/gibson2/./data/g_dataset 
More details here: https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/data/README.md
